import {
  Activity,
  AlertTriangle,
  ArrowRight,
  ArrowUp,
  Briefcase,
  Building,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  Clock,
  Droplet,
  Globe,
  Info,
  Layout,
  Layers,
  Lightbulb,
  MapPin,
  MessageSquare,
  Mic,
  PhoneCall,
  Search,
  Send,
  Shield,
  ShieldCheck,
  Shuffle,
  Store,
  ThumbsUp,
  Trash2,
  Users,
  Video,
  Volume2,
  Wrench,
  Zap,
} from 'lucide-react';

const iconMap = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  briefcase: Briefcase,
  building: Building,
  calendar: Calendar,
  check: Check,
  'check-circle': CheckCircle,
  'check-circle2': CheckCircle2,
  'check-square': CheckSquare,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  clock: Clock,
  droplet: Droplet,
  globe: Globe,
  info: Info,
  layout: Layout,
  layers: Layers,
  lightbulb: Lightbulb,
  'map-pin': MapPin,
  'message-square': MessageSquare,
  mic: Mic,
  'phone-call': PhoneCall,
  search: Search,
  send: Send,
  shield: Shield,
  'shield-check': ShieldCheck,
  shuffle: Shuffle,
  store: Store,
  'thumbs-up': ThumbsUp,
  'trash2': Trash2,
  users: Users,
  video: Video,
  'volume-2': Volume2,
  wrench: Wrench,
  zap: Zap,
};

export default function Icons({ name, className, size = 24 }) {
  const Icon = iconMap[name];
  if (!Icon) return null;
  return <Icon className={className} size={size} aria-hidden="true" />;
}
