import {
  Activity,
  AlertTriangle,
  ArrowRight,
  ArrowUp,
  Briefcase,
  Building,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ClipboardList,
  Clock,
  Droplet,
  Eye,
  FileText,
  Globe,
  Home,
  Image,
  Info,
  KeyRound,
  Layout,
  Layers,
  Lightbulb,
  Lock,
  LogOut,
  MapPin,
  MessageSquare,
  Mic,
  Package,
  PenLine,
  PhoneCall,
  Play,
  Plus,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Shuffle,
  Store,
  ThumbsUp,
  Trash2,
  Truck,
  Upload,
  UserPlus,
  Users,
  Video,
  Volume2,
  Wrench,
  X,
  Zap,
} from 'lucide-react';

const iconMap = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  briefcase: Briefcase,
  building: Building,
  calendar: Calendar,
  check: Check,
  'check-circle': CheckCircle,
  'check-circle2': CheckCircle2,
  'check-square': CheckSquare,
  'clipboard-list': ClipboardList,
  clock: Clock,
  droplet: Droplet,
  eye: Eye,
  'file-text': FileText,
  globe: Globe,
  home: Home,
  image: Image,
  info: Info,
  key: KeyRound,
  layout: Layout,
  layers: Layers,
  lightbulb: Lightbulb,
  lock: Lock,
  'log-out': LogOut,
  'map-pin': MapPin,
  'message-square': MessageSquare,
  mic: Mic,
  package: Package,
  pen: PenLine,
  'phone-call': PhoneCall,
  play: Play,
  plus: Plus,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  shuffle: Shuffle,
  store: Store,
  'thumbs-up': ThumbsUp,
  'trash2': Trash2,
  truck: Truck,
  upload: Upload,
  'user-plus': UserPlus,
  users: Users,
  video: Video,
  'volume-2': Volume2,
  wrench: Wrench,
  x: X,
  zap: Zap,
};

export default function Icons({ name, className, size = 24 }) {
  const Icon = iconMap[name];
  if (!Icon) return null;
  return <Icon className={className} size={size} aria-hidden="true" />;
}
